pool:
  name: 'dev-access'

stages:
- stage: Deploy
  jobs:
  - job: DeployMongoDB
    displayName: 'Deploy MongoDB to Kubernetes Namespace three-tier'
    steps:
    - task: Kubernetes@1
      displayName: 'Deploy MongoDB to Kubernetes'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: K8s_Connection  # âœ… FIXED
        azureResourceGroup: 'dev-env'
        kubernetesCluster: 'dev-cluster'
        namespace: 'three-tier'
        command: 'apply'
        arguments: '-f DB/database.yml'
